### ISSUE TITLE
Possibility of a more detailed README

### ISSUE THREAD

**Issue by ruidazeng** [SuprDewd/CompetitiveProgramming#6]
Do you think a more detailed README file describing each source code file in the "code" folder might be made available in the future?

**Comment by SuprDewd** [comment]
That's not a bad idea! I'll see what I can do.

Was there any code in particular that you were interested in?

Thanks for stopping by my training contest on Kattis yesterday, it was nice having some company. :)

**Comment by ruidazeng** [comment]
Thanks for getting back so quickly! 

I am mostly interested in the algorithmic files without the `.test` postfix. I have had experience implementing the easier ones like Dinic's and Dijikstra's, but I lack experience in implementing some other ones (unfortunately, there are some that I have never even heard of) and would like to see a brief explanation.

In addition, I am also interested in the "tricks" sub-folder as well.

**Comment by ruidazeng** [comment]
Thanks for getting back so quickly! 

I am mostly interested in the algorithmic files without the `.test` postfix. I have had experience implementing the more well-known ones like Dinic's and Dijikstra's, but I do lack experience in implementing some other ones (unfortunately, there are some that I have never even heard of) and would like to see a brief explanation.

In addition, I am also exceedingly interested and intrigued by source codes in the "tricks" sub-folder as well.
